# Funding configuration for GitHub Sponsors
# https://docs.github.com/github/administering-a-repository/displaying-a-sponsor-button

github: [dmenezes007]
# patreon: # your-patreon-username
# ko_fi: # your-ko-fi-username
# custom: ['https://www.paypal.me/yourpaypal']
